@startuml
'https://plantuml.com/class-diagram

interface Subject {
    registerObserver();
    removeObserver();
    notifyObservers();
}

interface Observer {
    update();
}

class ConcreteSubject {
    registerObserver();
    removeObserver();
    notifyObservers();

    getState();
    setState();
}

class ConcreteObserver {
    update();
}

Subject <|.. ConcreteSubject
Observer <|.. ConcreteObserver
Subject -> Observer
ConcreteSubject <- ConcreteObserver

@enduml