@startuml
'https://plantuml.com/class-diagram

interface Subject {
    request()
}

class RealSubject {
    request()
}

class Proxy {
    request()
}

Subject <|.. RealSubject
Subject <|.. Proxy
RealSubject <- Proxy

@enduml