@startuml
'https://plantuml.com/class-diagram

interface Product

class ConcreteProduct

interface Creator {
    factoryMethod()
    anOperation()
}

class ConcreteCreator {
    factoryMethod()
}

Creator <|.. ConcreteCreator
ConcreteCreator -> ConcreteProduct
Product <|.. ConcreteProduct

@enduml